test fix
from failed vercel builds, not related to my changes

Failed to compile.
./src/components/codeKeywords/keywordSelector.tsx:153:7
Type error: Type 'false | ReactPortal' is not assignable to type 'ReactNode'.
  Type 'ReactPortal' is not assignable to type 'ReactNode'.
    Type 'import("/vercel/path0/node_modules/@types/react-dom/node_modules/@types/react/index").ReactPortal' is not assignable to type 'React.ReactPortal'.
      Types of property 'children' are incompatible.
        Type 'import("/vercel/path0/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
          Type 'ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
            Property 'children' is missing in type 'ReactElement<unknown, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
  151 |         </span>
  152 |       </KeywordDropdown>
> 153 |       {isMounted &&
      |       ^
  154 |         createPortal(<AnimatePresence>{selector}</AnimatePresence>, document.body)}
  155 |     </Fragment>
  156 |   );
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1