Dart and Flutter Integrations Shared in platform docs correctly (#13030)
* Move all Dart and Flutter Integrations to Includes

- creates a subdirectory in includes for dart integrations
- from here these can be easily re-used by Dart and/or Flutter Docs
- the Dart integrations functionally remain the same
- Flutter now has all Dart integrations as well

* fix routing int naming

* fix regressions

- i made changes to mdxComponents.ts to allow simpler includes for dart and flutter
- caused a regression for other includes related to PlatformIdentifier
- this fixes that, there were errors in the build in vercel related to User Feedback Go FastHTTP, but was found in Python and other places. It is now resolved

* test fix

from failed vercel builds, not related to my changes

Failed to compile.
./src/components/codeKeywords/keywordSelector.tsx:153:7
Type error: Type 'false | ReactPortal' is not assignable to type 'ReactNode'.
  Type 'ReactPortal' is not assignable to type 'ReactNode'.
    Type 'import("/vercel/path0/node_modules/@types/react-dom/node_modules/@types/react/index").ReactPortal' is not assignable to type 'React.ReactPortal'.
      Types of property 'children' are incompatible.
        Type 'import("/vercel/path0/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
          Type 'ReactElement<unknown, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
            Property 'children' is missing in type 'ReactElement<unknown, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
  151 |         </span>
  152 |       </KeywordDropdown>
> 153 |       {isMounted &&
      |       ^
  154 |         createPortal(<AnimatePresence>{selector}</AnimatePresence>, document.body)}
  155 |     </Fragment>
  156 |   );
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

* remove changes to ts

* revert

* Update yarn.lock

* fix flutter integration list

* add integrations table

* Update index.mdx

* revert: Remove yarn.lock changes

---------

Co-authored-by: Giancarlo Buenaflor <giancarlo_buenaflor@yahoo.com>