Deno arguments are not in the correct order
When testing this Deno CLI complained about the order of arguments in the script

```me@me deno-edge-hello-world % deno run index.ts --allow-net=xxxxx.ingest.sentry.io

Permission flags have likely been incorrectly set after the script argument.
To grant permissions, set them before the script argument. For example:
    deno run --allow-read=. main.js
error: Module not found "file:///Users/steveneubank/Desktop/deno-edge-hello-world/index.ts".````